--- #YAML:1.0
name:                UNIVERSAL-exports
version:             0.05
abstract:            ~
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_03
author:              ~
distribution_type:   module
requires:     
    Exporter::Lite:                0.01
    Test::More:                    0.47
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
